/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_openhft_chronicle_queue_batch_BatchAppenderNative */

#ifndef _Included_net_openhft_chronicle_queue_batch_BatchAppenderNative
#define _Included_net_openhft_chronicle_queue_batch_BatchAppenderNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_openhft_chronicle_queue_batch_BatchAppenderNative
 * Method:    writeMessages
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_net_openhft_chronicle_queue_batch_BatchAppenderNative_writeMessages
  (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
