= Chronicle Queue Utilities
Neil Clifford
:toc: macro
:toclevels: 3
:css-signature: demo
:toc-placement: macro
:icons: font

toc::[]

This document describes Chronicle Queue utility problems that have been created to help in the maintainance of your Chronicle Queue environment.


== Chronicle Reader utility

Chronicle Reader allows you to specify a Chronicle Queue folder and export the queue message data to text in standard output (`stdout`).

To run the Chronicle Reader utility using Maven:

[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"
....

You can specify arguments that tailor the way that the Chronicle Reader utility behaves. For example:

=== Command-line arguments
The following table lists the available command line option arguments:

.Command-line arguments

|===
|Argument |Description
|`-d`
|Mandatory. The directory containing the source chronicle queue files.
|`-i`
|Displays data containing this regular expression.
|`-e`
|Do not display data containing this regular expression.
|`-f`
|Follow - wait for new data to arrive.
|`-m`
|Show a maximum of this many messages from the end of the data set.
|`-n`
|Start reading from this index point.
|`-h`
|Print this help and exit.
|===

The following file contains the Chronicle Reader utility code:
....
C:\Users\Neil\IdeaProjects\Chronicle-Queue\src\main\java\net\openhft\chronicle\queue\ChronicleReaderMain.java
....
=== Command-line examples

The following examples show how the option arguments can be used:

==== Export data from a queue

To write out the data from a queue that exists in `/data/queue`:

[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"  -Dexec.args="-d /data/queue"
....

==== Follow a queue

Following a queue ensures that the latest messages are written out to Standard-Out. It will wait, and append new messages as they arrive on the queue.

To follow a queue:

[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"  -Dexec.args="-d /data/queue -f"
....

==== Use regular expressions

To export data from a queue which includes only messages containing `USD`:

[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"  -Dexec.args="-d /data/queue -i USD"
....

To display records that contain certain string values: For example:

===== `USD`, *and* `CHI-X` - Include
[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"  -Dexec.args="-d /data/queue -i USD" -i "CHI-X"
....

===== `USD`, *but not* `CHI-X` - Exclude
[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"  -Dexec.args="-d /data/queue -i USD" -e "CHI-X"
....

==== Maximum message history

To export (up to) the last `1000` messages from a queue:

[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"  -Dexec.args="-d /data/queue -m 1000"
....

==== Index points

To follow a queue from the index point `0x123ABE`:

[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"  -Dexec.args="-d /data/queue -f -n 0x123ABE"
....

==== Help

To display the help message:

[source, java]
....
$ mvn exec:java -Dexec.mainClass="net.openhft.chronicle.queue.ChronicleReaderMain"  -Dexec.args="-h"
....

NOTE: The `-h` argument cannot be used in conjunction with other arguments.

