source 'https://rubygems.org'

gem 'asciidoctor-pdf', github: 'asciidoctor/asciidoctor-pdf', branch: 'HEAD' 
gem 'prawn-table', github: 'prawnpdf/prawn-table', branch: 'HEAD' 
gem 'rghost' 
gem 'rouge' 
