site:
  title: Chronicle Queue
  start_page: chronicle-queue:introduction:introduction.adoc
  # The following URL is only used when building locally. In the future, this should be set to the URL
  # where the page is really served
  url: /build
content:
  sources:
    - url: https://github.com/OpenHFT/Chronicle-Queue
      # Only generate from git tags (and not branches)
      branches: [develop]
      start_path: docs/antora
      tags: [testdoc]
ui:
  bundle:
    url: ui-bundle.zip # The UI bundle (page styling) is in Chronicle-Antora library.
  supplemental_files: ./supplemental_ui
    #path: ui.yml
    #  contents: |
    #    static_files: [ .nojekyll ]
    #  path: .nojekyll
asciidoc:
  attributes:
    page-pagination: true
    extensions:
      - highlightjs
# Uncomment the below if you want to build the page to another directory. The default dir is /build
#output:
#  dir:
