= Encryption (Enterprise Edition Feature)

Chronicle Queue Enterprise introduces the ability to encrypt your message queues and the constituent messages.

IMPORTANT: Encrypted queues are written to disk in their encrypted state. +
 +
Encrypted queues are replicated in their encrypted state. +
 +
The same encryption key must be available when accessing these encrypted queue files.

All standard AES key lengths (AES-128, AES-192, or AES-256 bits) are supported by default.
To encrypt messages use `SingleChronicleQueueBuilder.aesEncryption()` method when creating a queue and pass a key with length 128 or 192 or 256 bits as the argument (`byte[] keyBytes`).
The AES key length is determined based on the length of the `keyBytes` argument in the `aesEncryption()` method.
The following example creates a queue encrypted with AES-128.

.Creating encrypted queue
[source,java]
----
// A 128-bit key for AES-128, use 192 or 256 bits key for AES-192 and AES-256 respectively.
private static final byte[] SECURE_KEY = {(byte) 0x45, (byte) 0x83, (byte) 0x78, (byte) 0x33, (byte) 0x21, (byte) 0x95,        (byte) 0xA5, (byte) 0xCA, (byte) 0x12, (byte) 0x44, (byte) 0xFF, (byte) 0xD3, (byte) 0x04, (byte) 0x9A,                (byte) 0xB2, (byte) 0x77};

try (ChronicleQueue queue = SingleChronicleQueueBuilder.builder()
          .path("queueDirectory")
          .aesEncryption(SECURE_KEY)
          .build()) {
                 ...
        }
----

== AES 64-bit encryption

AES 64-bit encryption can be used by specifying `aesEncryption` at queue build time, and supplying an 8-bit encryption key.

For example:
[source, java]
....
public SingleChronicleQueueBuilder aesEncryption(@Nullable byte[] keyBytes) {
        if (keyBytes == null) {
            codingSuppliers(null, null);
            return this;
        }
        SecretKeySpec key = new SecretKeySpec(keyBytes, "AES");
        Supplier<BiConsumer<BytesStore, Bytes<?>>> encodingSupplier = () -> new VanillaCipher(Cipher.ENCRYPT_MODE, key);
        Supplier<BiConsumer<BytesStore, Bytes<?>>> decodingSupplier = () -> new VanillaCipher(Cipher.DECRYPT_MODE, key);
        codingSuppliers(encodingSupplier, decodingSupplier);
        messageHeader(MessageHeader.SALT_64, MessageHeader.SALT_64);
        return this;
    }
....

== Customer specified encryption
You can supply a bespoke encryption method to encrypt your messages using, perhaps, a more complex encryption method.

For example, you could perhaps combine encryption with salting, and/or compression.

Another example could be to write simple custom code that will encrypt the more important messages, while saving on overhead by not encrypting unimportant messages.

To enable this form of queue encryption, specify `codingSuppliers` at queue build time and supply the bespoke encryption method.

For example:

[source, java]
....
public SingleChronicleQueueBuilder codingSuppliers(@Nullable Supplier<BiConsumer<BytesStore, Bytes<?>>> encodingSupplier,
                                                           @Nullable Supplier<BiConsumer<BytesStore, Bytes<?>>> decodingSupplier) {
        if ((encodingSupplier == null) != (decodingSupplier == null))
            throw new UnsupportedOperationException("Both encodingSupplier and decodingSupplier must be set or neither");
        this.encodingSupplier = encodingSupplier;
        this.decodingSupplier = decodingSupplier;
        return this;
    }
....

'''

<<../README.adoc#,Back to Chronicle Queue>>

