= Release Notes
Chronicle Developers
:toc: macro
:toclevels: 1
:css-signature: demo
:toc-placement: macro
:icons: font

toc::[]

Release Notes for the following versions are available.

'''
== Release 4.6.13

This release was made available on 17th August 2017, and includes the following changes:

- Update Chronicle-Core dependency to 1.9.3
- Fix for issue #367

'''
== Release 4.6.11

This release was made available on 1st August 2017, and includes the following changes:

- The `-d` parameter is now mandatory when running `ChronicleReader`.
- `ChronicleReader` now uses a `Pauser` instead of a fixed length delay.

'''
== Changes from 4.4.0 to 4.5.0

- Improved support for binary messages (Bytes based instead of Wire based) in Queue
- A number of performance improvements to support replication.
- Fix some concurrent writer bugs.
- Improve handling of corrupted Queue with automatic recover via a RecoveryStrategy
- Changed createAppender() to acquireAppender() to make it clear you don't get a new one each time.
- Reduce the period for monitoring messages from every second to every 10 seconds.
- Deprecate the TEXT form of Queue. You can use ChronicleQueue.dump() and DumpQueueMain to dump a queue as text.
- Deprecate direct constructor calls to SingleChronicleQueueBuilder
- Adding TEST2_DAILY for up to 512 entries and TEST_HOURLY.
- Removed lastIndex(), you need to use a tailer.ToEnd() as it's a moving target.
- Removed support for zero length messages. No clean way of handling them at the moment.
- Improve cleanup of resources on a close().
- Support Tailer direction() as either TailerDirection.NONE, FORWARD, or BACKWARD
- Code simplification after review.

'''